---
abstract: 'Lingua::IND::Words2Nums currently can handle real numbers in normal and scientific form in the order of hundreds of trillions.'
author:
  - 'Steven Haryanto <sh@hhh.indoglobal.com>'
build_requires:
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-IND-Words2Nums
requires:
  Perl6::Export::Attrs: 0
  strict: 0
  warnings: 0
version: 0.044
